---
name: AnonChat
version: 1.0.1
main: NhanAZ\AnonChat\Main
src-namespace-prefix: NhanAZ\AnonChat
api: 5.0.0
author: NhanAZ
website: https://github.com/NhanAZ
description: "Allows players to chat anonymously"
...
